### PR TITLE
Dynamic Programming Initialization

### PR DESCRIPTION
**Pull request by Sand3r-**
Introduces implementation of dynamic programming initialization of expectation maximization algorithm based on paper [Initializing the EM Algorithm for Univariate Gaussian, Multi-Component, Heteroscedastic Mixture Models by Dynamic Programming Partitions](https://www.worldscientific.com/doi/pdf/10.1142/S0219876218500123).

More info enclosed in commit message.

### CODE REVIEW

**Review by Regis128 — DISMISSED** [review]
Seems good to me, but firstly fix codefactor and appveyor

**Comment by Sand3r-** [comment]
[Implement Splitter Segment Decomposer](https://trello.com/c/gLHHF4DH/514-implement-splitter-segment-decomposer)

**Comment by Sand3r-** [comment]
CodeFactor issues have been corrected. Appveyor's build is doing just fine, it's the artifacts that cause it to show up as 'failed'

**Review by Daroslaw — APPROVED** [review]
Good job

**Review by Regis128 — APPROVED** [review]

**Pull request merged**
